# Dependencies
markdown:            redcarpet
highlighter:         true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Vignesh Krishnamoorthy
tagline:             ': Is this the real life?'
description:         'The mind of a guy named me and my work'
url:                 http://vigneshkrishnamoorthy.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Vignesh Krishnamoorthy
  url:               https://twitter.com/vignkri
  email:             k.vignesh.krish@gmail.com

# Custom vars
version:             1.0.0
