markdown: redcarpet
highlighter: null
permalink: /:title

url:vigneshkrishnamoorthy.github.io
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed